/*
 * JSP generated by Resin Professional 4.0.66 (built Mon, 29 Nov 2021 04:23:00 PST)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.util.*;
import java.io.*;
import malgnsoft.db.*;
import malgnsoft.util.*;

public class _index__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=utf-8");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    
    //root \u00ed\u008f\u00b4\u00eb\u008d\u0094 \u00ea\u00b2\u00bd\u00eb\u00a1\u009c\u00eb\u00a5\u00bc \u00ec\u00a7\u0080\u00ec\u00a0\u0095\u00ed\u0095\u0098\u00eb\u008a\u0094 \u00ea\u00b2\u00bd\u00ec\u009a\u00b0 \u00ec\u0082\u00ac\u00ec\u009a\u00a9\u00ed\u0095\u0098\u00eb\u008a\u0094 \u00ec\u00a0\u0084\u00ec\u0097\u00ad\u00eb\u00b3\u0080\u00ec\u0088\u0098
    String docRoot = Config.getDocRoot();

    //db connection \u00ec\u0084\u00a4\u00ec\u00a0\u0095 \u00ec\u00a0\u0095\u00eb\u00b3\u00b4\u00eb\u00a5\u00bc \u00ec\u00a0\u0080\u00ec\u009e\u00a5\u00ed\u0095\u0098\u00eb\u008a\u0094 \u00ec\u00a0\u0084\u00ec\u0097\u00ad\u00eb\u00b3\u0080\u00ec\u0088\u0098
    String jndi = Config.getJndi();

    //\u00eb\u00a0\u0088\u00ec\u009d\u00b4\u00ec\u0095\u0084\u00ec\u009b\u0083 \u00ed\u008e\u0098\u00ec\u009d\u00b4\u00ec\u00a7\u0080\u00ec\u009d\u0098 \u00ea\u00b2\u00bd\u00eb\u00a1\u009c\u00eb\u00a5\u00bc \u00ec\u00a7\u0080\u00ec\u00a0\u0095\u00ed\u0095\u00a0 \u00ea\u00b2\u00bd\u00ec\u009a\u00b0 \u00ec\u0082\u00ac\u00ec\u009a\u00a9\u00ed\u0095\u0098\u00eb\u008a\u0094 \u00ec\u00a0\u0084\u00ec\u0097\u00ad\u00eb\u00b3\u0080\u00ec\u0088\u0098
    String tplRoot = Config.getDocRoot() + "/html";

    //\u00ed\u008c\u008c\u00ec\u009d\u00bc \u00ec\u0097\u0085\u00eb\u00a1\u009c\u00eb\u0093\u009c \u00ec\u00a7\u0080\u00ec\u00a0\u0095 \u00ea\u00b2\u00bd\u00eb\u00a1\u009c \u00ec\u00a0\u0084\u00ec\u0097\u00ad \u00eb\u00b3\u0080\u00ec\u0088\u0098
    String dataDir = Config.getDataDir();

    //\u00ec\u0097\u0085\u00eb\u00a1\u009c\u00eb\u0093\u009c \u00ed\u008c\u008c\u00ec\u009d\u00bc \u00ea\u00b2\u00bd\u00eb\u00a1\u009c url \u00ec\u00a0\u0084\u00ec\u0097\u00ad \u00eb\u00b3\u0080\u00ec\u0088\u0098
    String webUrl = Config.getWebUrl();

    //\u00ec\u009b\u00b9\u00ed\u008f\u00ac\u00ed\u008a\u00b8 \u00ec\u00a0\u0084\u00ec\u0097\u00ad \u00eb\u00b3\u0080\u00ec\u0088\u0098
    int port = request.getServerPort();
    if(port != 80) webUrl += ":" + port;

    //\u00ec\u009b\u00b9 \u00ea\u00b0\u009d\u00ec\u00b2\u00b4 \u00ec\u0083\u009d\u00ec\u0084\u00b1
    Malgn m = new Malgn(request, response, out);

    //\u00ed\u008f\u00bc \u00ea\u00b0\u009d\u00ec\u00b2\u00b4 \u00ec\u0083\u009d\u00ec\u0084\u00b1
    Form f = new Form();
    f.setRequest(request);

    //\u00ed\u008e\u0098\u00ec\u009d\u00b4\u00ec\u00a7\u0080 \u00ea\u00b0\u009d\u00ec\u00b2\u00b4 \u00ec\u0083\u009d\u00ec\u0084\u00b1
    Page p = new Page();
    p.setRequest(request);
    p.setPageContext(pageContext);
    p.setWriter(out);




    out.write(_jsp_string1, 0, _jsp_string1.length);
    

response.sendRedirect("/board_cjh/list.jsp");


  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -8439189455271529488L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("index.jsp"), -2520468478777089693L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("init.jsp"), 1072411392911731118L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string1;
  private final static char []_jsp_string0;
  static {
    _jsp_string1 = "\r\n\r\n\r\n".toCharArray();
    _jsp_string0 = "\r\n\r\n".toCharArray();
  }
}
